#!/bin/sh

# This normalization will also run check and fix routines
psfnormalize -p checkfix=fix source/masters/SourceSerifMaster-ExtraLightItalic.ufo
psfnormalize -p checkfix=fix source/masters/SourceSerifMaster-Italic.ufo
psfnormalize -p checkfix=fix source/masters/SourceSerifMaster-BlackItalic.ufo
psfnormalize -p checkfix=fix source/masters/SourceSerifMaster-ExtraLight.ufo
psfnormalize -p checkfix=fix source/masters/SourceSerifMaster-Regular.ufo
psfnormalize -p checkfix=fix source/masters/SourceSerifMaster-Black.ufo

# Following sync will copy psnames and glyphorder updates to all fonts
psfsyncmasters source/SourceSerifPro-Roman.designspace source/SourceSerifPro-Italic.designspace
