#!/bin/sh

# This normalization will also run check and fix routines
psfnormalize -p checkfix=fix source/masters/SourceSerif-Italic_0.ufo
psfnormalize -p checkfix=fix source/masters/SourceSerif-Italic_1.ufo
psfnormalize -p checkfix=fix source/masters/SourceSerif-Italic_2.ufo
psfnormalize -p checkfix=fix source/masters/SourceSerif-Roman_0.ufo
psfnormalize -p checkfix=fix source/masters/SourceSerif-Roman_1.ufo
psfnormalize -p checkfix=fix source/masters/SourceSerif-Roman_2.ufo

# Following sync will copy psnames and glyphorder updates to all fonts
psfsyncmasters source/SourceSerifPro-Roman.designspace source/SourceSerifPro-Italic.designspace
