#!/bin/sh

# Produce individual UFOs from Glyphs files
psfglyphs2ufo source/masters/SourceSerifProRoman.glyphs source/masters
psfglyphs2ufo source/masters/SourceSerifProItalic.glyphs source/masters

./preflight
